# Generated by Django 5.0.6 on 2024-06-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
